services:

  mongodb:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: fastfood
    ports:
      - "27017:27017"
    networks:
      - local-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongodb:27017/fastfood?authSource=admin
    networks:
      - local-network
    depends_on:
      - mongodb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - MONGODB_URL=mongodb://root:rootpassword@mongodb:27017/fastfood?authSource=admin
        - PRODUCTION_SERVICE_URL=http://order-product-app:8081
    ports:
      - "8082:8082"
    container_name: order-service-status-app
    networks:
      - local-network


networks:
  local-network:
    external: true