name: CI - Release
on: 
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean install -DskipTests
   test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Run tests
      run: mvn test jacoco:report -Dmaven.javadoc.skip=true

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: target/site/jacoco/jacoco.xml
   sonar:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Download coverage report
      uses: actions/download-artifact@v4
      with:
        name: coverage-report
    
    - name: Extract artifactId from pom.xml
      id: extract-artifact-id
      run: echo "ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV

    - name: Run SonarQube analysis
      run: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        -Dsonar.projectKey=${{ env.ARTIFACT_ID }} 
        -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }} 
        -Dsonar.host.url=${{ vars.SONAR_HOST_URL }} 
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        -Dsonar.qualitygate.wait=true

        


